apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bpu0q7gb3-dotnet-basic
  janus-idp.io/tekton: bpu0q7gb3-dotnet-basic
  backstage.io/kubernetes-id: bpu0q7gb3-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bpu0q7gb3-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
